version: '3.8'
services: 
  postgres:
    image: postgres:13.4
    volumes:
      - postgres-data:/data/db
    restart: always
    expose:
      - "5432"
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: postgres
      POSTGRES_DB: my_database
  api:
    image: online-shopping-store:1.0.0
    container_name: online-shopping-store
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    networks: 
      - nestjs_network
    depends_on: 
      - postgres
    links:
      - postgres
    restart: always
    environment: 
      DATABASE_URL: postgres://postgres:mysecretpassword@172.17.0.1:5432/my_database
volumes:
  postgres-data: {}
networks: 
  nestjs_network:
    driver: bridge