version: '3.8'
services: 
  mongo:
    image: mongo:latest
    container_name: mongo-db
    volumes:
      - mongo-database:/data/db
    restart: always
    expose:
      - "27017"
    ports:
      - 27017:27017
  api:
    image: online-shopping-store:1.0.0
    container_name: online-shopping-store
    build: .
    command: npm run start:dev
    ports:
      - 3000:3000
    networks: 
      - nestjs_network
    depends_on: 
      - mongo
    links:
      - mongo
    restart: always
volumes:
  mongo-database: {}
networks: 
  nestjs_network:
    driver: bridge